version: "3" #version of docker compose
services:    #each service is a container to will be created
    node-app: #name of the service or container 
        volumes:
            - ./:/app
            - /app/node_modules
        environment: 
            - NODE_ENV=development
        command: npm run dev #this override the Dockerfile CMD       